name:                fibonacci-hs
version:             0.1.0.0
github:              "minoki/fibonacci-hs"
license:             BSD3
author:              "ARATA Mizuki"
maintainer:          "minorinoki@gmail.com"
copyright:           "2019 ARATA Mizuki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/minoki/fibonacci-hs#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -O3

library:
  source-dirs: src

executables:
  fibonacci-hs-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - fibonacci-hs

tests:
  fibonacci-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fibonacci-hs
